---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "extract the tar/zipped file"
      become: true
      unarchive:
        src: /home/ubuntu/artifact.tar.gz
        dest: /home/ubuntu/
        remote_src: yes
        owner: ubuntu
        group: ubuntu

  roles:
    - deploy
