- name: 'update apt packages'
  become: yes
  apt:
    update_cache: yes

- name: 'upgrade packages'
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: 'install dependencies'
  become: true
  apt:
    name: ['nodejs', 'npm', 'tar', 'gzip', 'python3']
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    # production: yes
    state: present
  
# extract the tar/zipped file
- name: 'extract the tar/zipped file'
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend-app
    remote_src: yes
    owner: ubuntu
    group: ubuntu

# install backend dependencies
- name: 'install backend-app dependencies'
  become: true
  npm:
    path: /home/ubuntu/backend-app
    state: present

# stop the app
# - name: 'stop the app'
#   become: true
#   pm2:
#     path: /home/ubuntu/backend-app
#     state: absent

# start the app
- name: 'start the app'
  become: true
  shell: |
    cd /home/ubuntu/backend-app
    npm cache clean --force
    npm install
    # stop the app
    pm2 stop all
    pm2 start npm -- run start
  register: starting_app




