- name: Make backend-app directory
  file:
    path: /home/ubuntu/backend-app
    state: directory

- name: 'copy zipped file'
  become: yes
  copy:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: 'Where are we?'
  become: yes
  shell: pwd && ls -la && echo 'May be we are here...'
  
# extract the tar/zipped file
- name: 'extract the tar/zipped file'
  become: true
  unarchive:
    src: /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu/backend-app
    remote_src: yes
    owner: ubuntu
    group: ubuntu

# install backend dependencies
- name: 'install backend-app dependencies'
  become: true
  shell: |
    cd /home/ubuntu/backend-app
    npm install

# - name: 'stop all running node processes'
#   become: true
#   ignore_errors: true
#   command: pm2 stop default # this 
    
# start the app
- name: 'start the app'
  become: true
  shell: |
    cd /home/ubuntu/backend-app
    pm2 start npm -- start
  register: backend_app

- debug:
    msg: "{{ backend_app.stdout_lines }}"




